### ISSUE TITLE
Переход на PHP 5.4 и выше

### ISSUE THREAD

**Issue by rsajob** [limb-php-framework/limb#101]
Очень бы хотелось. Планируется вообще? Сам пытался перевести, сходу не получилось.

**Comment by p-kislitskiy** [comment]
Перешли на php 5.5 (https://github.com/limb-php-framework/limb/pull/112) без поддержки предыдущих версий.
Для работы с <= 5.3 используйте код по тегу [Limb2014.1](https://github.com/limb-php-framework/limb/tree/Limb2014.1)
